version: "3"
services:
  filebeat:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    command:
      - /start.sh
    container_name: filebeat
    environment:
      - PATH=/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: filebeat
    image: oktacsm/csm-apac:csm-apac-filebeat
    networks:
      - bridge
    restart: unless-stopped
    stdin_open: true
