version: "3"
services:
  elasticsearch:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    command:
      - eswrapper
    container_name: elasticsearch
    entrypoint:
      - /bin/tini
      - /usr/local/bin/docker-entrypoint.sh
    environment:
      - discovery.type=single-node
      - PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ELASTIC_CONTAINER=true
    hostname: elasticsearch
    image: oktacsm/csm-apac:elasticsearch-7-11-1
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    volumes:
      - ##########[Specify host path here]##########:/var/lib/elasticsearch
      - ##########[Specify host path for index here]##########: /usr/share/elasticsearch/data
    working_dir: /usr/share/elasticsearch
