version: "3"
services:
  csm-apac-ldap:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    container_name: csm-apac-ldap
    entrypoint:
      - /container/tool/run
    environment:
      - 'LDAP_ORGANISATION=CSM APAC'
      - LDAP_DOMAIN=csm-apac.com
      - LDAP_ADMIN_PASSWORD=Pa55word2
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    hostname: csm-apac-ldap
    image: oktacsm/csm-apac:csm-apac-openldap
    ipc: private
    networks:
      - bridge
    ports:
      - 389:389/tcp
    stdin_open: true
networks:
  bridge:
    external: true
