version: "3"
services:
  csm-apac-ldap:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    command:
      - --d
    container_name: csm-apac-ldap
    entrypoint:
      - /container/tool/run
    environment:
      - 'LDAP_ORGANISATION=CSM APAC'
      - LDAP_DOMAIN=csm-apac-1.duckdns.org
      - LDAP_ADMIN_PASSWORD=[PASSWORD HERE]
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    hostname: csm-apac-ldap
    image: oktacsm/csm-apac:csm-apac-openldap
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:07
    ports:
      - 389:389/tcp
    restart: unless-stopped
