version: "3"
services:
  splunk-1:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    command:
      - start-service
    container_name: splunk-1
    entrypoint:
      - /sbin/entrypoint.sh
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=[PASSWORD]  ####ENTER CUSTOM PASSWORD###
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - container=oci
      - SCLOUD_URL=https://github.com/splunk/splunk-cloud-sdk-go/releases/download/v1.7.0/scloud_v4.0.0_linux_amd64.tar.gz
      - PYTHON_VERSION=3.7.9
      - SPLUNK_HOME=/opt/splunk
      - SPLUNK_GROUP=splunk
      - SPLUNK_USER=splunk
      - TMPSPLUNKDIR=/opt/splunk/tmp
      - TMPETCDIR=/opt/splunk/tmp/etc
      - SPLUNK_ROLE=splunk_standalone
      - SPLUNK_ANSIBLE_HOME=/opt/ansible
      - ANSIBLE_USER=ansible
      - ANSIBLE_GROUP=ansible
      - CONTAINER_ARTIFACT_DIR=/opt/container_artifact
      - PYTHON_GPG_KEY_ID=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
      - SPLUNK_DEFAULTS_URL=
    hostname: splunk-1
    image: splunk/splunk:latest
    labels:
      architecture: x86_64
      build-date: 2020-12-10T01:55:47.415057
      com.docker.compose.config-hash: 38cd6da2491b1a84d1c2ccffcf4904a3e4e15d85f10d87dca81fffc30ae70a26
      com.docker.compose.container-number: 1
      com.docker.compose.oneoff: False
      com.docker.compose.project: splunk
      com.docker.compose.project.config_files: docker-compose.yml
      com.docker.compose.project.working_dir: /home/kent/splunk
      com.docker.compose.service: splunk
      com.docker.compose.version: 1.25.0
      com.redhat.build-host: cpt-1003.osbs.prod.upshift.rdu2.redhat.com
      com.redhat.component: ubi8-minimal-container
      com.redhat.license_terms: "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI"
      description: 'Splunk Enterprise is a platform for operational intelligence.
        Our software lets you collect, analyze, and act upon the untapped value of
        big data that your technology infrastructure, security systems, and business
        applications generate. It gives you insights to drive operational performance
        and business results.'
      distribution-scope: public
      io.k8s.description: 'The Universal Base Image Minimal is a stripped down image
        that uses microdnf as a package manager. This base image is freely redistributable,
        but Red Hat only supports Red Hat technologies through subscriptions for Red
        Hat products. This image is maintained by Red Hat and updated regularly.'
      io.k8s.display-name: 'Red Hat Universal Base Image 8 Minimal'
      io.openshift.expose-services: ""
      io.openshift.tags: 'minimal rhel8'
      maintainer: support@splunk.com
      name: splunk
      release: 1
      summary: 'UBI 8 Docker image of Splunk Enterprise'
      url: "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.3-230"
      vcs-ref: c868247d5bda77e997533ece37f1d3816497909e
      vcs-type: git
      vendor: splunk
      version: 8.1.2
    networks:
      - bridge
    ports:
      - 8001:8000/tcp
    restart: unless-stopped
    user: ansible
    volumes:
      - /home/kent/splunk/etc:/opt/splunk/etc  ###Define customer directory###
      - /home/kent/splunk/var:/opt/splunk/var  ###Define customer directory###
    working_dir: /opt/splunk
