version: "3"
services:
  csm-apac-ldap-agent:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    command:
      - /start.sh
    container_name: csm-apac-ldap-agent
    environment:
      - PATH=/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: csm-apac-ldap-agent
    image: oktacsm/csm-apac:csm-apac-ldap-agent
    memswap_limit: -1
    networks:
      - bridge
    stdin_open: true
    volumes:
      - /tmp:/tmp
networks:
  bridge:
    external: true