version: "3"
services:
  csm-apac-phpldapadmin:
    container_name: csm-apac-phpldapadmin
    entrypoint:
      - /bootstrap.sh
    environment:
      - LDAP_HOST=10.0.0.4
      - LDAP_PORT=389
      - LDAP_DOMAIN=dc=csm-apac-1,dc=duckdns,dc=org
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: cca55136819f
    image: docfactory/phpldapadmin:latest
    ipc: private
    labels:
      maintainer: docfactory
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:05
    networks:
      - bridge
    ports:
      - 800:80/tcp
