version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - /media/data-02/monitoring/prometheus:/etc/prometheus
      - ./prometheus.yml:/media/data-02/monitoring/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    restart: always
  exporter:
    image: prom/node-exporter:latest
    container_name: prometheus-node-exporter
    hostname: csm-apac-1
    ports:
      - 9100:9100
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    restart: always
