version: "3"
services:
  kibana:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    command:
      - /usr/local/bin/kibana-docker
    container_name: kibana
    entrypoint:
      - /bin/tini
    environment:
      - SERVER_NAME=kibana.server.com
      - ELASTICSEARCH_HOSTS=http://192.168.1.117:9200   #########[Change as per your environment]#########
      - PATH=/usr/share/kibana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ELASTIC_CONTAINER=true
    hostname: kibana
    image: oktacsm/csm-apac:csm-apac-kibana
    ports:
      - 5601:5601/tcp
    user: kibana
    working_dir: /usr/share/kibana
