version: "3"
services:
  csm-apac-phpldapadmin:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    container_name: csm-apac-phpldapadmin
    entrypoint:
      - /bootstrap.sh
    environment:
      - LDAP_HOST=oci-4.ddns.net
      - LDAP_PORT=389
      - LDAP_DOMAIN=dc=csm-apac,dc=com
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: csm-apac-phpldapadmin
    image: oktacsm/csm-apac:csm-apac-phpldapadmin
    networks:
      - bridge
    ports:
      - 800:80/tcp
networks:
  bridge:
    external: true
